### ISSUE TITLE
Vectara 0.3.3. breaks the readme example

### ISSUE THREAD

**Issue by istranic** [vectara/python-sdk#46]
The query example in the readme doesn't work after the latest release 0.3.3.

https://github.com/vectara/python-sdk?tab=readme-ov-file#querying-the-corpora

```
---------------------------------------------------------------------------
PydanticUserError                         Traceback (most recent call last)
Cell In[9], [line 1](vscode-notebook-cell:?execution_count=9&line=1)
----> [1](vscode-notebook-cell:?execution_count=9&line=1) search = SearchCorporaParameters(
      [2](vscode-notebook-cell:?execution_count=9&line=2)         corpora=[
      [3](vscode-notebook-cell:?execution_count=9&line=3)             KeyedSearchCorpus(
      [4](vscode-notebook-cell:?execution_count=9&line=4)                 corpus_key=corpus_key,
      [5](vscode-notebook-cell:?execution_count=9&line=5)                 metadata_filter="",
      [6](vscode-notebook-cell:?execution_count=9&line=6)                 lexical_interpolation=0.005,
      [7](vscode-notebook-cell:?execution_count=9&line=7)             )
      [8](vscode-notebook-cell:?execution_count=9&line=8)         ],
      [9](vscode-notebook-cell:?execution_count=9&line=9)         context_configuration=ContextConfiguration(
     [10](vscode-notebook-cell:?execution_count=9&line=10)             sentences_before=2,
     [11](vscode-notebook-cell:?execution_count=9&line=11)             sentences_after=2,
     [12](vscode-notebook-cell:?execution_count=9&line=12)         ),
     [13](vscode-notebook-cell:?execution_count=9&line=13)         reranker=CustomerSpecificReranker(
     [14](vscode-notebook-cell:?execution_count=9&line=14)             reranker_id="rnk_272725719"
     [15](vscode-notebook-cell:?execution_count=9&line=15)         ),
     [16](vscode-notebook-cell:?execution_count=9&line=16)     )
     [17](vscode-notebook-cell:?execution_count=9&line=17) generation = GenerationParameters(
     [18](vscode-notebook-cell:?execution_count=9&line=18)         response_language="eng",
     [19](vscode-notebook-cell:?execution_count=9&line=19)         enable_factual_consistency_score=True,
     [20](vscode-notebook-cell:?execution_count=9&line=20)     )
     [22](vscode-notebook-cell:?execution_count=9&line=22) client_on_prem.query(
     [23](vscode-notebook-cell:?execution_count=9&line=23)     query="Am I allowed to bring pets to work?",
     [24](vscode-notebook-cell:?execution_count=9&line=24)     search=search,
     [25](vscode-notebook-cell:?execution_count=9&line=25)     generation=generation
     [26](vscode-notebook-cell:?execution_count=9&line=26)     
     [27](vscode-notebook-cell:?execution_count=9&line=27) )

    [... skipping hidden 1 frame]

File ~/Environments/rag/lib/python3.11/site-packages/pydantic/_internal/_mock_val_ser.py:99, in MockValSer.__getattr__(self, item)
     [97](https://file+.vscode-resource.vscode-cdn.net/Users/A0513810/Code/~/Environments/rag/lib/python3.11/site-packages/pydantic/_internal/_mock_val_ser.py:97) # raise an AttributeError if `item` doesn't exist
     [98](https://file+.vscode-resource.vscode-cdn.net/Users/A0513810/Code/~/Environments/rag/lib/python3.11/site-packages/pydantic/_internal/_mock_val_ser.py:98) getattr(self._val_or_ser, item)
---> [99](https://file+.vscode-resource.vscode-cdn.net/Users/A0513810/Code/~/Environments/rag/lib/python3.11/site-packages/pydantic/_internal/_mock_val_ser.py:99) raise PydanticUserError(self._error_message, code=self._code)

PydanticUserError: `SearchCorporaParameters` is not fully defined; you should define `ChainReranker`, then call `SearchCorporaParameters.model_rebuild()`.
```

**Comment by istranic** [comment]
The example worked in 0.2.44, and that's what we use in our applications. It's not clear how we need to change out search code to make it work with the latest release.

**Comment by nikron** [comment]
Yes, we're tracking this and are looking to get a fix out.

**Comment by nikron** [comment]
The newest SDK, 0.3.4 should fix this issue.

**Comment by istranic** [comment]
I still have the issue and I confirmed that `vectara.__verison__` is 3.4.0

**Comment by istranic** [comment]
Here's the code I'm running. It's the same as the readme except that I change the model via `generation_preset_name`

```
search = SearchCorporaParameters(
        corpora=[
            KeyedSearchCorpus(
                corpus_key=corpus_key,
                metadata_filter="",
                lexical_interpolation=0.005,
            )
        ],
        context_configuration=ContextConfiguration(
            sentences_before=1,
            sentences_after=1,
        ),
        reranker=CustomerSpecificReranker(
            reranker_id="rnk_272725719"
        ),
    )
generation = GenerationParameters(
        generation_preset_name="mockingbird-1.0-2024-07-16",
        response_language="eng",
        enable_factual_consistency_score=True,
        # model_parameters = ModelParameters(llm_name = "mockingbird-1.0")
    )



response = client_on_prem.query(
    query="What are these docs about?",
    search=search,
    generation=generation
    
)
```

**Comment by istranic** [comment]
Hey @nikron do you have any updates here?

**Comment by nikron** [comment]
Yes, sorry, there was a mistake in 0.3.4. We released again in 3.4.5, and it should work there.

**Comment by istranic** [comment]
Thx, it's working.
